### ISSUE TITLE
TypeError: theme is not a function

### ISSUE THREAD

**Issue by tomhayes** [kraKero/tailwind-fieldtype#5]
HI, 

I've installed the addon and ran `php please krakero:tailwind-config`

I get the following error: 

```
Config file found...
Installing NPM Dependencies...
Converting tailwind config to PHP...
/var/www/html/node_modules/tailwindcss/stubs/config.full.js:7
      ...theme('colors'),
         ^

TypeError: theme is not a function
    at Object.accentColor (/var/www/html/node_modules/tailwindcss/stubs/config.full.js:7:10)
    at /var/www/html/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/node_modules/tailwindcss/lib/util/resolveConfig.js:114:65
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (/var/www/html/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/node_modules/tailwindcss/lib/util/resolveConfig.js:112:30)
    at resolveConfig (/var/www/html/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/node_modules/tailwindcss/lib/util/resolveConfig.js:217:12)
    at resolveConfig (/var/www/html/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/node_modules/tailwindcss/resolveConfig.js:6:10)
    at Object.<anonymous> (/var/www/html/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js:18:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

Node.js v18.17.1
```

Am I missing something?

**Comment by vmitchell85** [comment]
Can you post your `tailwind.config.js` file?

**Comment by tomhayes** [comment]
> @vmitchell85 Can you post your `tailwind.config.js` file?

sure, here you go - thanks! 

```
//--------------------------------------------------------------------------
// Tailwind configuration
//--------------------------------------------------------------------------
//
// Use the Tailwind configuration to completely define the current sites
// design system by adding and extending to Tailwinds default utility
// classes. Various aspects of the config are split inmultiple files.
//

/** @type {import('tailwindcss').Config} */
module.exports = {
    // The various configurable Tailwind configuration files.
    presets: [
        require('tailwindcss/defaultConfig'),
        require('./tailwind.config.typography.js'),
        require('./tailwind.config.site.js'),
    ],
    // Configure files to scan for utility classes (JIT).
    content: [
        './resources/views/**/*.blade.php',
        './resources/views/**/*.html',
        './resources/js/**/*.js',
        './vendor/studio1902/**/*.blade.php',
        './vendor/studio1902/**/*.html',
        './vendor/studio1902/**/*.js',
    ],
    safelist: [
        'button-slant-right-double',
        'button-slant-full',
        {
            pattern: /(bg|text|border|fill)-(bf-tomato|bf-tomato-light|bf-tomato-lightest|bf-robin-egg|bf-rich-black-100|bf-rich-black-80|bf-rich-black-60|bf-rich-black-40)/,
            variants: ['hover','active','group-hover'],
        },
    ]
}

```

**Comment by vmitchell85** [comment]
@tomhayes Does it show the same error if you run `php artisan krakero:tailwind-config` instead of `php please krakero:tailwind-config`?

**Comment by tomhayes** [comment]
> krakero:tailwind-config

Yes, same error!

**Comment by vmitchell85** [comment]
@tomhayes Looks like this has something to do with how Peak has their tailwind config setup... It's erroring inside tailwindcss on a function. I'll have to dig into it more later. Sorry it's not working for you.

**Comment by tomhayes** [comment]
> @tomhayes Looks like this has something to do with how Peak has their tailwind config setup... It's erroring inside tailwindcss on a function. I'll have to dig into it more later. Sorry it's not working for you.

Thanks for looking into it! Looks like a really useful addon, I hope you can get it sorted!

**Comment by marcorieser** [comment]
As soon as I remove the default config from the presets array it works:
```js
module.exports = {
  presets: [
    // require('tailwindcss/defaultConfig'),
    require('./tailwind.config.typography.js'),
    require('./tailwind.config.peak.js'),
    require('./tailwind.config.site.js'),
  ],
  ...
}
```

Seems like the underlying npm package can not handle the `require('tailwindcss/defaultConfig')`.

@tomhayes 
The generated css before and after removing `require('tailwindcss/defaultConfig')`, is identical so I'd suggest giving it a try and give feedback if you ran into issues.

**Comment by marcorieser** [comment]
Just started a discussion in Peak Discord if we can remove that line by default.

**Comment by robdekort** [comment]
It can be removed. It was there for legacy reasons and isn't needed anymore.

**Comment by vmitchell85** [comment]
Well that makes my job easier. I'll update the Read Me with a troubleshooting section. Thanks @robdekort @marcorieser and @tomhayes!
